title: Harry's Site
logo: /assets/img/logo.png
# description: Minimal is a theme for GitHub Pages.
description: A high school student
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
